---
image: "ruby:3.2"

variables:
  RAILS_ENV: test

before_script:
  - ruby -v
  - which ruby
  - gem --version
  - gem install bundler --no-document
  - bundle config path vendor
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

stages:
  - test

test:
  stage: test
  cache:
    paths:
      - vendor
  script:
    - bundle exec rspec
    - bundle exec rubocop
